document.addEventListener('DOMContentLoaded', () => {
    const tabs = require('./modules/tabs')
    const cards = require('./modules/cards')
    const modal = require('./modules/modal')
    const slider = require('./modules/slider')
    const calculator = require('./modules/calculator')
    const timer = require('./modules/timer')
    const server = require('./modules/server')
    tabs()
    cards()
    modal()
    slider()
    calculator()
    timer()
    server()
})